
import { Inter } from 'next/font/google'
import './global.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ring Containers',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor: 'rgba(36, 35, 36, 0.932)'}} className={inter.className}>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lobster+Two&family=Roboto&display=swap" rel="stylesheet"/>
        {children}
      </body>
    </html>
  )
}
