
import { Inter } from 'next/font/google'
import './global.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ring Containers',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor: 'rgba(36, 35, 36, 0.932)'}} className={inter.className}>{children}</body>
    </html>
  )
}
